### ISSUE TITLE
How is the performance compared with for loop? 

### ISSUE THREAD

**Issue by ysmood** [wesovilabs/koazee#12]
Wonder how much the overhead of reflection is.

**Comment by ivancorrales** [comment]
Hey @ysmood , actually is the price that we need to pay for providing a generic solution... Trust me that I've been so focused on improving performance, and an article comparing Koazee with other frameworks is available here:  https://medium.com/@ivan.corrales.solera/koazee-vs-go-funk-vs-go-linq-caf8ef18584e

**Comment by ysmood** [comment]
I'm very interested in your idea, nice job. I know this is a silly question, but it won't be bad to let people know the cost to they have to pay for the benefits, which might help you to tune the project better.

Here's a discussion that you might want to subscript https://github.com/golang/go/issues/15292

**Comment by ivancorrales** [comment]
Awesome @ysmood  I really appreciate your advice!!!
