### ISSUE TITLE
Allow user functions to return an optional error

### ISSUE THREAD

**Issue by flowonyx** [wesovilabs/koazee#26]
Some functions would be nice to use in Map, Reduce, and ForEach but they return not only the desired value, but a possible error. An example would be `strconv.Atoi` which could be used to map strings to ints but cannot currently be used because of the error value.

It would be useful to stop processing of a stream when an error occurs in the supplied function and make that error available to the user.

I have already implemented this for my own use and would be happy to share what I have. (You can see the updated code at https://github.com/flowonyx/koazee/tree/error-functions). The only thing I know I am missing is that I completely skip the `dispatch` method if the supplied function returns an error. I assume that the dispatch functions are generated, but I could not find any code to generate them.

I also do not know what impact this has on performance, though I suspect it should be minimal.

**Comment by ivancorrales** [comment]
For sure! Thanks a million @flowonyx would you mind doing a PR? We can comment it together over the PR

Thanks a million!

**Comment by ivancorrales** [comment]
That was merged with PR from @flowonyx
