### ISSUE TITLE
Update Readme with contributors

### ISSUE THREAD

**Issue by ivancorrales** [wesovilabs/koazee#35]
It would be nice add link to contributors as part of Readme

So far a public tweet thanks

https://twitter.com/wesovilabs/status/1080357122557255680?s=19

@xuyz  @u5surf @flowonyx

**Comment by flowonyx** [comment]
I'm not sure if this is the appropriate place to discuss this, but I noticed that none of the pull requests from anyone but yourself were actually merged, just closed. I don't know if I'm missing something here, but I can see that none of the code in the pull request I submitted was merged. Are you doing work offline on it and will merge it later? I'm just confused about it, is all. Thanks.

**Comment by ivancorrales** [comment]
All the pull request have been merged. 

![image](https://user-images.githubusercontent.com/12560219/50624912-a439c700-0f24-11e9-9696-bc8578420f8d.png)
![image](https://user-images.githubusercontent.com/12560219/50624925-c16e9580-0f24-11e9-9205-b21b6dddcf5a.png)
![image](https://user-images.githubusercontent.com/12560219/50624931-c9c6d080-0f24-11e9-93a4-4bbaba49bc15.png)

I will double check why your PR was not  merged, because I thought It was merged... If IT was my mistake I really apologize for this.

**Comment by u5surf** [comment]
Hi, I'm willing to add an explaination of DropWhile and IndexesOf in this ReadMe after more two features I will be implemented(GroupBy, Append). Can you wait a while okay?

**Comment by ivancorrales** [comment]
Sure, this sounds great! The success of doing open source is all of us we can contribute

And of course any operation you wish just open a new issue

Thanks again

**Comment by flowonyx** [comment]
I see that my pull request is now merged. Thanks! I hope my contribution was helpful.

**Comment by ivancorrales** [comment]
It was so great your contribution. It was my fault...  I thought I had merged sorry for that!
