### ISSUE TITLE
DropLeft operation

### ISSUE THREAD

**Issue by ivancorrales** [wesovilabs/koazee#45]
var elements = []int{10,12,7,41,5,6}
res:=koazee.StreamOf(elements).DropLeft(12).Out().Val()
fmt.Println(res)

// [10]

**Comment by mentol310** [comment]
I would like to address this issue.
So there is a question.

In dropRight issue #44

> This operations will be used to drop elements in the steam on the right of the given element

It was written.
DropLeft expected values ​​are not as follows?

```
expect := []int{12,7,41,5,6}
actual := koazee.StreamOf([]int{10,12,7,41,5,6}).DropLeft(12).Out().Val()
assert.Equal(t, expect, actual)
```

**Comment by ivancorrales** [comment]
Hey @mentol310 I really appreciate your job!

Yes That was my thought when I create the issue. Your test would be perfect,

**Comment by aswinkarthik** [comment]
Could you close this issue if PR has already been merged?
